<a href="https://colab.research.google.com/github/26wh5a0501-dotcom/Nasscom/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
import numpy as np

# Create a 1D array with numbers from 0 to 99
arr1_1 = np.arange(0, 100)

print(arr1_1)
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
import numpy as np

# Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

print(arr1_2)
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
import numpy as np

# Create a 2x4 array filled with the number 7
arr1_3 = np.full((2, 4), 7)

print(arr1_3)
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
import numpy as np

# Create a 5x5 array with random integers between 10 and 50 (inclusive)
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print(arr1_4)




--- Task 1: Array Creation Shortcuts ---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]
[[37 35 39 31 36]
 [40 43 42 49 16]
 [39 10 15 48 11]
 [16 34 36 43 10]
 [28 42 33 12 24]]


In [5]:
# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
import numpy as np

print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.

val2_1 = data[2, 3]
print("2.1:", val2_1)

# 2.2 Extract the first row. Store it in 'row2_2'.

row2_2 = data[0]
print("2.2:", row2_2)

# 2.3 Extract the last column. Store it in 'col2_3'.

col2_3 = data[:, 3]
print("2.3:\n", col2_3)

# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
sub_arr2_4 = data[1:3, 0:2]
print("2.4:\n", sub_arr2_4)

# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.
filtered_elements2_5 = data[data > 100]
print("2.5:", filtered_elements2_5)





--- Task 2: Indexing and Slicing with Arrays ---

--- Task 2: Indexing and Slicing with Arrays ---
2.1: 120
2.2: [10 20 30 40]
2.3:
 [ 40  80 120 160]
2.4:
 [[ 50  60]
 [ 90 100]]
2.5: [110 120 130 140 150 160]


In [6]:
# Task 3: Conditional Operations

import numpy as np

print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array

print("Original Array:\n", arr3_1)

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print("\nArray after replacing values less than 10 with 0:\n", arr3_2)

#3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.

even_count3_3 = np.sum(arr3_1 % 2 == 0)
print("\nNumber of even elements:", even_count3_3)


--- Task 3: Conditional Operations ---
Original Array:
 [[ 1  2  6 10 15]
 [ 3  7  2 15  6]
 [12 12 11  5 10]
 [20  9  6  9  6]]

Array after replacing values less than 10 with 0:
 [[ 0  0  0 10 15]
 [ 0  0  0 15  0]
 [12 12 11  0 10]
 [20  0  0  0  0]]

Number of even elements: 11


In [7]:
# Task 4: Aggregation Functions
import numpy as np

print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
sum4_1 = np.sum(arr4_1)
print("4.1 Sum:", sum4_1)

# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.
mean_cols4_2 = np.mean(arr4_1, axis=0)
print("4.2 Mean of each column:", mean_cols4_2)

# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.
max_rows4_3 = np.max(arr4_1, axis=1)
print("4.3 Maximum value in each row:", max_rows4_3)

# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.
std4_4 = np.std(arr4_1)
print("4.4 Standard Deviation:", std4_4)


--- Task 4: Aggregation Functions ---
4.1 Sum: 84
4.2 Mean of each column: [11.          6.66666667 10.33333333]
4.3 Maximum value in each row: [12 15 20]
4.4 Standard Deviation: 5.2493385826745405


In [9]:
# Task 5: Reshaping and Flattening
import numpy as np
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)   # 1D array from 0 to 23

print("Original Array:")
print(arr5_1)

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2 = arr5_1.reshape(4, 6)
print("\n4x6 Array:")
print(reshaped_arr5_2)

# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
print("\n2x3x4 Array:")
print(reshaped_arr5_3)
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).

# 5.3 Flatten using ravel()
flattened_arr5_4 = reshaped_arr5_2.ravel()
print("\nFlattened using ravel():")
print(flattened_arr5_4)

# Flatten using flatten()
flattened_arr5_5 = reshaped_arr5_2.flatten()
print("\nFlattened using flatten():")
print(flattened_arr5_5)


--- Task 5: Reshaping and Flattening ---
Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4x6 Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

2x3x4 Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
# Task 6: Broadcasting

import numpy as np

print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.

result6_1 = arr6_1 + scalar
print("6.1 Result:")
print(result6_1)


# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2 = arr6_1 + vector
print("\n6.2 Result:")
print(result6_2)


--- Task 6: Broadcasting ---
6.1 Result:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

6.2 Result:
[[101 202 303]
 [104 205 306]
 [107 208 309]]


In [12]:
# Task 7: Copying vs. Viewing Arrays

import numpy as np

print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

print("Original Array:", original_arr7)

# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.

view_arr7 = original_arr7[:]

#     Modify the first element of 'view_arr7' to 99.
view_arr7[0] = 99
#     Observe how 'original_arr7' changes.
print("\nAfter modifying the view:")
print("View Array:", view_arr7)
print("Original Array:", original_arr7)


# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.

copy_arr7 = original_arr7.copy()

#     Modify the last element of 'copy_arr7' to 0.
copy_arr7[-1] = 0

#     Observe how 'original_arr7' remains unchanged.
print("\nAfter modifying the copy:")
print("Copy Array:", copy_arr7)
print("Original Array:", original_arr7)



--- Task 7: Copying vs. Viewing Arrays ---
Original Array: [1 2 3 4 5]

After modifying the view:
View Array: [99  2  3  4  5]
Original Array: [99  2  3  4  5]

After modifying the copy:
Copy Array: [99  2  3  4  0]
Original Array: [99  2  3  4  5]


In [17]:
# Task 8: Stacking and Splitting Arrays

import numpy as np

print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2],
                   [3, 4]])

arr8_b = np.array([[5, 6],
                   [7, 8]])

arr8_c = np.array([[9, 10],
                   [11, 12]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
print("8.1 Vertical Stack:")
print(vstack_arr8_1)

# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.

hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
print("\n8.2 Horizontal Stack:")
print(hstack_arr8_2)

# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.

combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))
print("\n8.3 Combined Array:")
print(combined_arr8_3)

# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.


print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

print("\nPart 3:")
print(part3)



--- Task 8: Stacking and Splitting Arrays ---
8.1 Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

8.2 Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]

8.3 Combined Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Part 1:
[[1 2]
 [3 4]]

Part 2:
[[5 6]
 [7 8]]

Part 3:
[[ 9 10]
 [11 12]]


In [18]:
# Task 9: Sorting and Searching
import numpy as np
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.

sorted_arr9_1 = np.sort(arr9_1)
print("9.1 Sorted 1D Array:")
print(sorted_arr9_1)

# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.

sorted_cols9_2 = np.sort(arr9_2d, axis=0)
print("\n9.2 Sorted Columns:")
print(sorted_cols9_2)


# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)

idx9_3 = np.where(arr9_1 == 9)
print("\n9.3 Index of value 9:")
print(idx9_3)

# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

max_idx9_4 = np.argmax(arr9_1)
print("\n9.4 Index of Maximum Value:")
print(max_idx9_4)


--- Task 9: Sorting and Searching ---
9.1 Sorted 1D Array:
[1 2 3 4 5 6 7 8 9]

9.2 Sorted Columns:
[[30 20 10]
 [60 50 40]
 [90 80 70]]

9.3 Index of value 9:
(array([4]),)

9.4 Index of Maximum Value:
4
